openapi: 3.0.0

info:
  title: MarketPlace Project
  version: 1.0.0

servers:
  - url: http://market.loc
    description: local dev api

tags:
  - name: HealthChecks
    description: Проверка состояния системы
  - name: Auth

paths:
  /api/market/v1/healthCheck:
    get:
      tags:
        - HealthChecks
      summary: Проверка состояния системы
      responses:
        '200':
          $ref: '#/components/responses/ok'

  /api/market/v1/auth/phone/request:
    $ref: './paths/auth/phone/request.yaml'
  /api/market/v1/auth/phone/sign-in:
    $ref: './paths/auth/phone/signIn.yaml'

  /api/market/v1/auth/email/request:
    $ref: './paths/auth/email/request.yaml'
  /api/market/v1/auth/email/sign-in:
    $ref: './paths/auth/email/signIn.yaml'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    ok:
      description: Ok
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: Ok
    error:
      description: error
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: error message
    tokens:
      description: Токены авторизации
      content:
        application/json:
          schema:
            properties:
              accessToken:
                type: string
              lifeTime:
                type: integer
              refreshToken:
                type: string
              type:
                type: string

  parameters:
    clientId:
      name: client-id
      in: header
      description: Id приложение клиента
      required: true
      schema:
        type: string
    clientSecret:
      name: client-secret
      in: header
      description: Ключ приложение клиента
      required: true
      schema:
        type: string

