openapi: 3.0.0
info:
  title: MarketPlace Project
  version: 1.0.0
servers:
  - url: 'http://market.loc'
    description: local dev api
tags:
  - name: HealthChecks
    description: Проверка состояния системы
  - name: Auth
paths:
  /api/market/v1/healthCheck:
    get:
      tags:
        - HealthChecks
      summary: Проверка состояния системы
      responses:
        '200':
          $ref: '#/components/responses/ok'
  /api/market/v1/auth/phone/request:
    post:
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  required: true
                  type: string
                  example: '+996772119663'
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '400':
          $ref: '#/components/responses/error'
        '422':
          description: null
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  errors:
                    type: object
                    properties:
                      phone:
                        type: array
                        items:
                          type: string
  /api/market/v1/auth/phone/sign-in:
    post:
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  required: true
                  type: string
                  example: '+996772119663'
                code:
                  required: true
                  type: string
                  example: '119663'
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '400':
          $ref: '#/components/responses/error'
        '422':
          description: null
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  errors:
                    type: object
                    properties:
                      phone:
                        type: array
                        items:
                          type: string
                      code:
                        type: array
                        items:
                          type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    ok:
      description: Ok
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: Ok
    error:
      description: error
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: error message
