openapi: 3.0.0
info:
  title: MarketPlace Project
  version: 1.0.0
servers:
  - url: 'http://market.loc'
    description: local dev api
tags:
  - name: HealthChecks
    description: Проверка состояния системы
  - name: Auth
paths:
  /api/market/v1/healthCheck:
    get:
      tags:
        - HealthChecks
      summary: Проверка состояния системы
      responses:
        '200':
          $ref: '#/components/responses/ok'
  /api/market/v1/auth/phone/request:
    post:
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  example: '+996772119663'
      responses:
        '200':
          $ref: '#/components/responses/ok'
components:
  responses:
    ok:
      description: Ok
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: Ok
